services:
  - type: web
    name: pixelsignal16
    runtime: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    branch: main
    envVars:
      - key: SHOPIFY_API_KEY
        value: your_api_key_here
      - key: SHOPIFY_API_SECRET
        value: your_api_secret_here
      - key: SCOPES
        value: read_products,write_products
      - key: SHOPIFY_APP_URL
        value: https://pixelsignal16.onrender.com
      - key: NODE_ENV
        value: production
      - key: FRONTEND_PORT
        value: "10000"
