services:
  - type: web
    name: pixelsignal16
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: vite preview --port $PORT
    envVars:
      - key: SHOPIFY_API_KEY
        value: your_api_key
      - key: SHOPIFY_API_SECRET
        value: your_api_secret
      - key: SCOPES
        value: read_products,write_products
      - key: SHOPIFY_APP_URL
        value: https://pixelsignal16.onrender.com
      - key: NODE_ENV
        value: production
