# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c2e051850c30de605c5e3adfe089d045"
name = "PixelSignal16"
handle = "pixelsignal16"
application_url = "https://copyrights-abandoned-receives-sample.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://copyrights-abandoned-receives-sample.trycloudflare.com/auth/callback",
  "https://copyrights-abandoned-receives-sample.trycloudflare.com/auth/shopify/callback",
  "https://copyrights-abandoned-receives-sample.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
